---
account:
  source:
    name: hkcnews
    id: 5138416
  target:
    name: dallmo
    id: 4292832 

endpoint:
  api_prefix:   https://3.basecampapi.com
  redirect_uri: https://dallmo.com/connector/basecamp
  auth_request: https://launchpad.37signals.com/authorization/new
  access_token: https://launchpad.37signals.com/authorization/token
  auth_test:    https://launchpad.37signals.com/authorization.json
