---
account:
  source:
    name: hkcnews
    id: 5138416
  target:
    name: dallmo
    id: 4292832 

api:
  url_prefix: https://3.basecampapi.com

redirect_uri: https://dallmo.com/connector/basecamp
